Add support for vimdoc
hedyhli/outline.nvim pull request #76
Opened 2024-06-26 14:36 UTC by oskarrrrrrr

I've added Vimdoc support, the implementation is very similar to that of Norg's. I included headings and tags in the outline, just headings provide very little information.

There seem to be quite a lot of edge cases that could be improved. For example, sometimes there are empty headings or headings that are not actual document headings but table headings. Sometimes there are multiple tags in one line, sometimes in multiple lines (but they refer to the same thing). The formatting seems quite inconsistent, even in the builtin documentation (e.g. the main page marks modeline as heading, other pages seem to get it right...). We could come up with some heuristics for the most common cases, for now I ignored all that.

Example below. 

<img width="1800" alt="image" src="https://github.com/hedyhli/outline.nvim/assets/12835846/52a168d7-b3e0-423b-a1fa-09eeeb50d4b4">

I used `Variable` kind for tags so that they can be easily filtered out.

I've encountered on issue, not sure if my change caused it. When there is a window with help file open and another with, for example, a lua file then the outline sidebar will show outline for the lua file always. For some reason the outline for help files seems to work only for one file and if there is another buffer in the same tab it will take over. Even switching between two help files won't work, the first one will be always shown in the sidebar. Other filetypes seem to work fine. I can try to debug that, but maybe someone has an idea what could be the reason?

2024-06-30 01:35 UTC, hedyhli commented
Thanks for this! I'll take a look at it soon.

> I've encountered on issue, not sure if my change caused it. When there is a window with help file open and another with, for example, a lua file then the outline sidebar will show outline for the lua file always. For some reason the outline for help files seems to work only for one file and if there is another buffer in the same tab it will take over. Even switching between two help files won't work, the first one will be always shown in the sidebar. Other filetypes seem to work fine. I can try to debug that, but maybe someone has an idea what could be the reason?

Currently outline looks for `buflisted` option to determine whether the symbols should be refreshed when we switch to a new buffer.

https://github.com/hedyhli/outline.nvim/blob/028e0bc8ad3d511e9fc1f0678594a608eb908ee5/lua/outline/sidebar.lua#L341-L345

This check is only done on "refresh", ie, when the cursor moves or text changed (governed by `outline_items.auto_update_events.items`), which means it prevents the outline items from updating when the user navigates from the code to things like floating windows (eg, `:LspStatus`).

I believe it makes sense to special case the `help` ft here (for instance, only ignore refresh if `buflisted` is false and `ft` is *not* `help`), now that vimdocs are now supported in outline.nvim.

2024-07-01 14:48 UTC, oskarrrrrrr commented
Thanks, changing this one line fixed the issue.

I got rid of "OutlineHelp" from the condition, because outline help buffer is created with 'buflisted' set to false.

2024-07-05 04:33 UTC, hedyhli requested changes
Firstly, please use 2 spaces for indents as it's used everywhere else. `stylua` (or `gg=G` with `shiftwidth=2`) can convert it all for you. Perhaps I should've included an `.editorconfig` sooner, my bad 😅

> There seem to be quite a lot of edge cases that could be improved. For example, sometimes there are empty headings or headings that are not actual document headings but table headings. Sometimes there are multiple tags in one line, sometimes in multiple lines (but they refer to the same thing). The formatting seems quite inconsistent, even in the builtin documentation (e.g. the main page marks modeline as heading, other pages seem to get it right...). We could come up with some heuristics for the most common cases, for now I ignored all that.

Thanks for your thorough testing -- I didn't encounter these issues during mine. What are some help pages you used that can reproduce this issue?

2024-07-05 04:33 UTC, hedyhli commented on lua/outline/config.lua
> +    priority = { 'lsp', 'coc', 'markdown', 'norg', 'vimdoc'},
Remember to reflect changes to the default config in the relevant section of readme too.

2024-07-05 04:33 UTC, hedyhli commented on lua/outline/providers/vimdoc.lua
Norg tree-sitter puts everything under a heading under the heading node. This makes it so headings' range extend until before the next sibling. The tree-sitter parser for vimdoc, however,  does not do this (headings range only span a single line, where the heading is defined); so we'll have to update the `range['end']` and `selectionRange['end']` ourselves.

The desired behaviour can be seen in this video (notice how the cursor is inbetween two headings, the node for the first heading is highlighted):

https://github.com/hedyhli/outline.nvim/assets/50042066/82986160-9dea-438d-9a12-7dd6bde1a8c5

For reference, something like this might work:
```diff
diff --git a/lua/outline/providers/vimdoc.lua b/lua/outline/providers/vimdoc.lua
index ddb242b..efdf853 100644
--- a/lua/outline/providers/vimdoc.lua
+++ b/lua/outline/providers/vimdoc.lua
@@ -83,6 +83,15 @@ function M.request_symbols(on_symbols, opts)
             level = captureLevel,
         }
 
+        if current.range then
+            current.range['end'] = { character = 0, line = new.range.start.line - 2 }
+            current.selectionRange = current.range
+        end
+        local prev_sibling = current.children[#current.children]
+        if prev_sibling then
+            prev_sibling.range['end'] = { character = 0, line = new.range.start.line - 2 }
+            prev_sibling.selectionRange = prev_sibling.range
+        end
         table.insert(current.children, new)
         current = new
     end
```

2024-07-05 13:59 UTC, oskarrrrrrr commented
> Thanks for your thorough testing -- I didn't encounter these issues during mine. What are some help pages you used that can reproduce this issue?

These are not big issues to be honest and maybe not as common as I initially thought, here are some examples.

Heading with no text (except for the tag):
<img width="1800" alt="Screenshot 2024-07-05 at 9 37 06 AM" src="https://github.com/hedyhli/outline.nvim/assets/12835846/9cbc88e4-9535-4317-ac41-20cc40257866">

Three tags in the same line:
<img width="1158" alt="Screenshot 2024-07-05 at 9 33 09 AM" src="https://github.com/hedyhli/outline.nvim/assets/12835846/65ca28d7-5071-446c-bff2-1d1173007334">

Two tags referring to the same thing in multiple lines:
<img width="1068" alt="Screenshot 2024-07-05 at 9 41 17 AM" src="https://github.com/hedyhli/outline.nvim/assets/12835846/06be509f-0b88-4822-8dde-e013ae932ef9">

Modeline is a header:
<img width="1158" alt="Screenshot 2024-07-05 at 9 33 51 AM" src="https://github.com/hedyhli/outline.nvim/assets/12835846/6f931842-5b47-46cb-9984-58511461b58b">

(you can see the help file name in the top left corner)

The examples with tags are not necessarily issues with the help file formatting. It's just that they take a lot of lines in the sidebar. Not a big deal probably.

2024-07-05 14:09 UTC, oskarrrrrrr commented
Here is an example where some tags for a heading are in the line before that heading:

<img width="1087" alt="Screenshot 2024-07-05 at 10 07 24 AM" src="https://github.com/hedyhli/outline.nvim/assets/12835846/12306852-b605-4b71-bde5-d21a318597cd">

2024-08-06 14:02 UTC, oskarrrrrrr commented on lua/outline/providers/vimdoc.lua
Your snippet worked for some cases but ultimately I ended up with a different approach to cover all cases.

2024-10-20 13:15 UTC, closed without merging